version: 2.1

orbs:
  linter: thekevjames/linter@0
  pytest: thekevjames/pytest@0

jobs:
  pypi:
    docker:
      - image: python:3.9.0-alpine
    steps:
      - run: apk add --no-cache git openssh-client
      - run: pip install twine
      - checkout
      - deploy:
          name: upload to pypi
          command: |
            python setup.py sdist bdist_wheel
            twine upload dist/*

  github:
    docker:
      - image: debian:buster-slim
    steps:
      - run: apt update -qy
      - run: apt install -qy hub git
      - checkout
      - run: hub release create -FCHANGELOG.md "${CIRCLE_TAG}"

workflows:
  run-jobs:
    jobs:
      - linter/pre-commit:
          python_version: 3.7.4
          filters:
            tags:
              only: /.*/

      - pytest/pytest:
          name: test-py36
          args: --cov=getchanges
          install_args: -r requirements.txt -r requirements.test.txt
          python_version: 3.6.9
          post-steps:
            - run: python setup.py check --restructuredtext --strict
          filters:
            tags:
              only: /.*/
      - pytest/pytest:
          name: test-py37
          args: --cov=getchanges
          install_args: -r requirements.txt -r requirements.test.txt
          python_version: 3.7.4
          post-steps:
            - run: python setup.py check --restructuredtext --strict
          filters:
            tags:
              only: /.*/

      - pypi:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
          requires:
            - linter/pre-commit
            - test-py36
            - test-py37

      - github:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
          requires:
            - linter/pre-commit
            - test-py36
            - test-py37
